#Server
server:  
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

<<<<<<< HEAD
spring:  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dorandb?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
=======
#MySql
spring:  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
>>>>>>> branch 'jungin' of https://github.com/jhatab/DORAN.git
    username: root
    password: 1234
#View
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#JSP수정시 서버 재시작없이 바로 적용될 수 있게 설정 
  devtools:
    livereload:
      enabled: true


#mybatis  
<<<<<<< HEAD
mybatis: 
  mapper-locations:
  - classpath:/mapper/**/mapper.xml  
  type-aliases-package: com.project.doran.**.vo

  
=======
#mybatis:#  mapper-locations:#  - classpath:/mapper/mapper.xml#  type-aliases-package: com.project.doran.**.vo
>>>>>>> branch 'jungin' of https://github.com/jhatab/DORAN.git
